---
title: "Homework5"
author: "Qianying Wu"
date: "2023-11-12"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

## Problem 1



## Problem 2

```{r}

# List all CSV files in the directory
file_paths <- list.files(path = "data", pattern = "\\.csv$", full.names = TRUE)

library(tidyverse)

process_file <- function(file_path) {
  # Read the file
  data <- read.csv(file_path)

  subject_id <- strsplit(basename(file_path), "[_.]")[[1]][2]

  if (grepl("con", file_path)) {
    arm <- "Control"
    }
  else{
    arm <- "Experimental"
    }

  data <- mutate(data, `Subject ID` = subject_id, Arm = arm)
  return(data)
}


combined_data <- purrr::map_df(file_paths, process_file)

combined_data


combined_data <- combined_data |> pivot_longer(
    cols = starts_with("week_"), 
    names_to = "Week",           
    values_to = "Observation"   
  ) |>
  mutate(
    Week = parse_number(Week),
    Arm = factor(Arm, levels = c("Control", "Experimental"))
  )

head(combined_data)

## Draw the spaghetti plot
ggplot(combined_data, aes(x = Week, y = Observation, group = `Subject ID`)) +
  geom_line(aes(color = Arm), alpha = 0.4) +  # Add transparency to lines
  geom_point(aes(color = Arm), alpha = 0.4) +
  theme_minimal() +
  labs(title = "Spaghetti Plot of Subject Observations Over Time",
       x = "Week",
       y = "Observation",
       color = "Group") +
  scale_color_manual(values = c("Control" = "blue", "Experimental" = "red"))
```


## Problem 3



First set the following design elements:

Fix n=30
Fix σ=5
Set μ=0. Generate 5000 datasets from the model

x∼Normal[μ,σ]

For each dataset, save μ̂ and the p-value arising from a test of H:μ=0 using α=0.05. Hint: to obtain the estimate and p-value, use broom::tidy to clean the output of t.test.

```{r}
set.seed(123)
n <- 30
sigma <- 5000
mu <- c(0, 1, 2, 3, 4, 5, 6)
iteration <- 5
alpha <- 0.05



stat_test <- function(n, sigma, mu, iteration, alpha){
  pval_list <- c()
  mu_hat_list <- c()
  rej_est_list <- c()
  
  for (i in 1:iteration){
    sample <- rnorm(n, mu, sigma)
    clean <- broom::tidy(t.test(sample, mu = 0))
    pvalue <- clean$p.value
    pval_list <- c(pval_list, pvalue)
    mu_hat <- clean$estimate
    mu_hat_list <- c(mu_hat_list, mu_hat)
    
    # store the rej_est_list with all the estimates that are rejected
    if (mu_hat < alpha ){
      rej_est <- clean$estimate
      rej_est_list <- c(rej_est_list, rej_est)
    }
    
  }
  power <- mean(pval_list < alpha)
  mean_estimate <- mean(mu_hat_list)
  if (length(rej_est_list) > 0){
    mean_est_rej <- mean(rej_est_list)
    # If nothing is rejected, the Value should be defined
  } else{
    mean_est_rej <- NA
  }
  
  return(c(power, mean_estimate, mean_est_rej))
}


power <- c()
mean_estimate <- c()
mean_est_rej <- c()

for (i in mu){
  result <- stat_test(n, sigma, i, iteration, alpha)
  power <- c(power, result[1])
  mean_estimate <- c(mean_estimate, result[2])
  mean_est_rej <- c(mean_est_rej, result[3])
  
}

power
mean_estimate
mean_est_rej







```


